// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvNn19xB3Nq8zWRlPVF-wxyinRGGJtVnA',
    appId: '1:751508936615:web:3eabd6e0584796d6428882',
    messagingSenderId: '751508936615',
    projectId: 'exampractice-f0a05',
    authDomain: 'exampractice-f0a05.firebaseapp.com',
    storageBucket: 'exampractice-f0a05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQw3zFEN9WaC1L3cgyQXy0ml8TRywOLiw',
    appId: '1:751508936615:android:b5274d5583f21765428882',
    messagingSenderId: '751508936615',
    projectId: 'exampractice-f0a05',
    storageBucket: 'exampractice-f0a05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzUNZPMtqrFRKdMz6cAW8v7MpyDM1FGaE',
    appId: '1:751508936615:ios:69dc640672bd0f9e428882',
    messagingSenderId: '751508936615',
    projectId: 'exampractice-f0a05',
    storageBucket: 'exampractice-f0a05.firebasestorage.app',
    iosBundleId: 'com.example.exampractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzUNZPMtqrFRKdMz6cAW8v7MpyDM1FGaE',
    appId: '1:751508936615:ios:69dc640672bd0f9e428882',
    messagingSenderId: '751508936615',
    projectId: 'exampractice-f0a05',
    storageBucket: 'exampractice-f0a05.firebasestorage.app',
    iosBundleId: 'com.example.exampractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvNn19xB3Nq8zWRlPVF-wxyinRGGJtVnA',
    appId: '1:751508936615:web:e52f040be4d45b29428882',
    messagingSenderId: '751508936615',
    projectId: 'exampractice-f0a05',
    authDomain: 'exampractice-f0a05.firebaseapp.com',
    storageBucket: 'exampractice-f0a05.firebasestorage.app',
  );
}
